# Generated by Django 3.1.7 on 2021-04-02 05:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cayxanh',
            fields=[
                ('ma_cay', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ten_cay', models.CharField(max_length=100)),
                ('chieucao', models.IntegerField()),
                ('vitri', models.CharField(max_length=100)),
                ('ngaytrong', models.DateField(verbose_name='Ngày trồng')),
                ('dacdiem', models.CharField(blank=True, max_length=200, null=True, verbose_name='Đặc điểm ')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='loaicay',
            fields=[
                ('ma_loai_cay', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='mã loại cây')),
                ('ten_loai_cay', models.CharField(max_length=100, verbose_name='tên loại cây')),
            ],
        ),
        migrations.CreateModel(
            name='nhanvien',
            fields=[
                ('ma_nhan_vien', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Mã nhân viên')),
                ('hoten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('gioitinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3)),
                ('dienthoai', models.IntegerField(default=0)),
                ('diachi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
            ],
        ),
        migrations.CreateModel(
            name='ranh_gioi',
            fields=[
                ('ma_ranh_gioi', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã ranh giới')),
                ('ten_ranh_gioi', models.CharField(max_length=100, verbose_name='Tên ranh giới')),
                ('type_ranh_gioi', models.CharField(choices=[('Phường', 'Phường'), ('Xã', 'Xã')], max_length=6, verbose_name='Loại ranh giới')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('ghichu', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tinhtrangcay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tinh_trang', models.CharField(max_length=100, verbose_name='tên tình trạng cây')),
            ],
        ),
        migrations.CreateModel(
            name='duonggiaothong',
            fields=[
                ('ma_duong', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Mã đường')),
                ('ten_duong', models.CharField(max_length=100, verbose_name='Tên đường')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('ghichu', models.CharField(blank=True, max_length=150, null=True)),
                ('ranh_gioi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlcayxanh.ranh_gioi', verbose_name='Tên ranh giới')),
            ],
        ),
        migrations.CreateModel(
            name='chamsoccay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cong_viec', models.CharField(max_length=100, verbose_name='Công việc')),
                ('ngay_cham_soc', models.DateField(verbose_name='Ngày chăm sóc')),
                ('cayxanh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlcayxanh.cayxanh', verbose_name='Cây xanh')),
                ('nhanvien_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlcayxanh.nhanvien', verbose_name='Nhân viên ')),
            ],
        ),
        migrations.AddField(
            model_name='cayxanh',
            name='duong_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlcayxanh.duonggiaothong', verbose_name='Tên đường giao thông'),
        ),
        migrations.AddField(
            model_name='cayxanh',
            name='loaicay_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlcayxanh.loaicay', verbose_name='Loại cây'),
        ),
        migrations.AddField(
            model_name='cayxanh',
            name='tinhtrang_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlcayxanh.tinhtrangcay', verbose_name='Tình trạng'),
        ),
    ]
